### ISSUE TITLE
Is there something wrong with my Settings? Why is the network disconnected!

### ISSUE THREAD

**Issue by shaozhai** [JonStratton/mesh-micro#1]
![Uploading IMG_20220322_160815.jpg…]()
![Uploading IMG_20220322_155057.jpg…]()
Is there something wrong with my Settings? Why is the network disconnected!

**Comment by JonStratton** [comment]
I cant see whatever screenshots you posted. If you want me to help looking at something, start by pasting the text content of "ip a". If you have more than one of these running, also run "sudo batctl n".

**Comment by shaozhai** [comment]
![16480017697702499563990981753105](https://user-images.githubusercontent.com/3293135/159610581-39a27406-d2a6-4676-82bf-8866f23edb1c.jpg)

**Comment by shaozhai** [comment]
![16480018339485018946283749019856](https://user-images.githubusercontent.com/3293135/159610718-07ddfa73-ab88-4f7e-a128-8b27ee4b5d08.jpg)

**Comment by shaozhai** [comment]
![16480019022713060766208157011944](https://user-images.githubusercontent.com/3293135/159610840-b7ca8aa8-a617-4ce3-85ee-78e5ec4a0b74.jpg)

**Comment by JonStratton** [comment]
Yes, that looks correct. The host with the Ethernet connection("Server") has an IP address of 192.168.200.1 on bat0. "bat n" shows that both computers are connected in a mesh. So they are meshed, there might be something else going on with the IPs or the bridging to the internet.

On the computer without the Ethernet connection("Client"), you should also run "ip a". You should see a "192.168.200.??" IP address for the bat0 interface. This means that the Server is acting as a DHCP server for the Client. If not, run "dhclient bat0" on the Client and see if it gets an IP address thats in the "192.168.200.??" range. 

If that is the case, you should be able to ping the Server from the Client ("ping 192.168.200.1"). Finally, if the connection is good, you should be able to ping the internet from the Client ("ping 8.8.8.8").

**Comment by shaozhai** [comment]
![IMG_20220324_175312](https://user-images.githubusercontent.com/3293135/159890583-0db504ea-34dc-4d9e-9007-9767d1808d9f.jpg)
![IMG_20220324_175412](https://user-images.githubusercontent.com/3293135/159890605-c5e730c8-0da0-4f75-8a6a-15b85e52e6c4.jpg)
![IMG_20220324_175447](https://user-images.githubusercontent.com/3293135/159890615-7490a091-acbf-4467-9b26-e96f2cdb4904.jpg)
Conf file mesh-micro.conf is not found in /etc/dnsmasq.d. Eth0 does not have an IP address. Bat0 has IP address 169.254.11.173

**Comment by JonStratton** [comment]
It looks like "iptables" was missing from the base install. This may have caused the "client" to not get a dhcp lease from the server.  You can probably correct this on the "server" without reinstalling by running "apt-get install iptables" and then rebooting.

Let me know if this doesn't fix your issue. And thanks for the heads up.

**Comment by shaozhai** [comment]
root@rock3a:~# apt-get install iptables
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
iptables is already the newest version (1.8.7-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.

**Comment by shaozhai** [comment]
Upgrade and the problem is still there
